services:
  etcd0:
    image: gcr.io/etcd-development/etcd:v3.6.2
    container_name: etcd0
    cap_add:
      - NET_ADMIN
    command: >
      /usr/local/bin/etcd
      --name etcd0
      --data-dir /etcd-data0
      --listen-client-urls http://0.0.0.0:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://etcd0:2380
      --advertise-client-urls http://etcd0:2379
      --initial-cluster etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      --initial-cluster-state new

  etcd1:
    image: gcr.io/etcd-development/etcd:v3.6.2
    container_name: etcd1
    cap_add:
      - NET_ADMIN
    command: >
      /usr/local/bin/etcd
      --name etcd1
      --data-dir /etcd-data1
      --listen-client-urls http://0.0.0.0:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://etcd1:2380
      --advertise-client-urls http://etcd1:2379
      --initial-cluster etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      --initial-cluster-state new

  etcd2:
    image: gcr.io/etcd-development/etcd:v3.6.2
    container_name: etcd2
    cap_add:
      - NET_ADMIN
    command: >
      /usr/local/bin/etcd
      --name etcd2
      --data-dir /etcd-data2
      --listen-client-urls http://0.0.0.0:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://etcd2:2380
      --advertise-client-urls http://etcd2:2379
      --initial-cluster etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      --initial-cluster-state new

networks:
  default:
    driver: bridge
